#-------------------------------------------------->
# makefile autogenerated by python script
# customize it following your own needs <3
#-------------------------------------------------->

# compiler / linker
CC := gcc

# flags for compilation & linking
CFLAGS := -Wall -Werror -Wpedantic -Wextra -MMD -MP
LDFLAGS :=

# folders
SRCDIR := .
BUILDDIR := build

# executables
EXEC1 := $(BUILDDIR)/samples/sample-one-exe-complex/main
EXEC2 := $(BUILDDIR)/samples/sample-multi-exe/main
EXEC3 := $(BUILDDIR)/samples/sample-multi-exe/test/buffer_test
EXEC4 := $(BUILDDIR)/samples/sample-multi-exe/test/memset_test
EXEC5 := $(BUILDDIR)/samples/sample-multi-exe/test/canbus_test
EXEC6 := $(BUILDDIR)/samples/sample-one-exe/test/canbus_test

# folders to include on compilation time
INCS := $(addprefix -I,$(shell find $(SRCDIR) -type f -name "*.h" | xargs dirname | sort | uniq))

# source files
SRC1 := samples/sample-one-exe-complex/lib/buffer/buffer.c \
	samples/sample-one-exe-complex/lib/canbus/canbus.c \
	samples/sample-one-exe-complex/lib/memset/memset.c \
	samples/sample-one-exe-complex/main.c
SRC2 := samples/sample-multi-exe/main.c \
	samples/sample-one-exe-complex/lib/buffer/buffer.c \
	samples/sample-one-exe-complex/lib/canbus/canbus.c \
	samples/sample-one-exe-complex/lib/memset/memset.c
SRC3 := samples/sample-multi-exe/test/buffer_test.c \
	samples/sample-one-exe-complex/lib/buffer/buffer.c \
	samples/sample-one-exe-complex/lib/unity/unity.c
SRC4 := samples/sample-multi-exe/test/memset_test.c \
	samples/sample-one-exe-complex/lib/memset/memset.c \
	samples/sample-one-exe-complex/lib/unity/unity.c
SRC5 := samples/sample-multi-exe/test/canbus_test.c \
	samples/sample-one-exe-complex/lib/buffer/buffer.c \
	samples/sample-one-exe-complex/lib/canbus/canbus.c \
	samples/sample-one-exe-complex/lib/unity/unity.c
SRC6 := samples/sample-one-exe/test/canbus_test.c \
	samples/sample-one-exe-complex/lib/buffer/buffer.c \
	samples/sample-one-exe-complex/lib/canbus/canbus.c \
	samples/sample-one-exe-complex/lib/unity/unity.c

# objects
OBJ1 := $(SRC1:%.c=$(BUILDDIR)/%.o)
OBJ2 := $(SRC2:%.c=$(BUILDDIR)/%.o)
OBJ3 := $(SRC3:%.c=$(BUILDDIR)/%.o)
OBJ4 := $(SRC4:%.c=$(BUILDDIR)/%.o)
OBJ5 := $(SRC5:%.c=$(BUILDDIR)/%.o)
OBJ6 := $(SRC6:%.c=$(BUILDDIR)/%.o)
OBJS := $(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4) $(OBJ5) $(OBJ6)

# targets ########################

# build all
build: $(EXEC1) $(EXEC2) $(EXEC3) $(EXEC4) $(EXEC5) $(EXEC6)

# run all
run: build
	@echo "**************************************************"
	@echo "Running all executables..."
	@echo "**************************************************"
	@echo ""
	@./$(EXEC1)
	@echo ""
	@./$(EXEC2)
	@echo ""
	@./$(EXEC3)
	@echo ""
	@./$(EXEC4)
	@echo ""
	@./$(EXEC5)
	@echo ""
	@./$(EXEC6)

# compile/link: main
$(EXEC1): $(OBJ1)
	@$(CC) $^ $(LDFLAGS) -o $@

# compile/link: main2
$(EXEC2): $(OBJ2)
	@$(CC) $^ $(LDFLAGS) -o $@

# compile/link: buffer_test
$(EXEC3): $(OBJ3)
	@$(CC) $^ $(LDFLAGS) -o $@

# compile/link: memset_test
$(EXEC4): $(OBJ4)
	@$(CC) $^ $(LDFLAGS) -o $@

# compile/link: canbus_test
$(EXEC5): $(OBJ5)
	@$(CC) $^ $(LDFLAGS) -o $@

# compile/link: canbus_test2
$(EXEC6): $(OBJ6)
	@$(CC) $^ $(LDFLAGS) -o $@

# targets for each object
$(BUILDDIR)/%.o: %.c
	@mkdir -p $(dir $@)
	@$(CC) -c $< -o $@ $(CFLAGS) $(INCS)

# run: main
main: $(EXEC1)
	@echo ""
	@echo "**************************************************"
	@echo "Running main..."
	@echo "**************************************************"
	@echo ""
	@./$(EXEC1)

# run: main2
main2: $(EXEC2)
	@echo ""
	@echo "**************************************************"
	@echo "Running main2..."
	@echo "**************************************************"
	@echo ""
	@./$(EXEC2)

# run: buffer_test
buffer_test: $(EXEC3)
	@echo ""
	@echo "**************************************************"
	@echo "Running buffer_test..."
	@echo "**************************************************"
	@echo ""
	@./$(EXEC3)

# run: memset_test
memset_test: $(EXEC4)
	@echo ""
	@echo "**************************************************"
	@echo "Running memset_test..."
	@echo "**************************************************"
	@echo ""
	@./$(EXEC4)

# run: canbus_test
canbus_test: $(EXEC5)
	@echo ""
	@echo "**************************************************"
	@echo "Running canbus_test..."
	@echo "**************************************************"
	@echo ""
	@./$(EXEC5)

# run: canbus_test2
canbus_test2: $(EXEC6)
	@echo ""
	@echo "**************************************************"
	@echo "Running canbus_test2..."
	@echo "**************************************************"
	@echo ""
	@./$(EXEC6)

help:
	@clear
	@echo "******************** Targets *********************"
	@echo "help: to print this menu"
	@echo "build: to compile and link all sources (default)"
	@echo "run: to run all the executables"
	@echo "main: to run main"
	@echo "main2: to run main2"
	@echo "buffer_test: to run buffer_test"
	@echo "memset_test: to run memset_test"
	@echo "canbus_test: to run canbus_test"
	@echo "canbus_test2: to run canbus_test2"
	@echo "clean: to remove the build folder"
	@echo "**************************************************"
	@echo ""

clean:
	@rm -rf $(BUILDDIR)

.PHONY: help build run main main2 buffer_test memset_test canbus_test \
	canbus_test2 clean

-include $(OBJS:.o=.d)
